using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Impstation.Teg.UI.Panels;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class TemperaturePanel : BoxContainer
{
}
