using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.Teg;
using Content.Client._Impstation.Teg.UI.Panels;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.Teg.UI;

[UsedImplicitly]
[GenerateTypedNameReferences]
public sealed partial class TegWindow : FancyWindow
{
    public TegWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(TegUIState state)
    {
        CircA.UpdateState(state.CircA);
        CircB.UpdateState(state.CircB);
    }
}
